### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by shuber2** [aklomp/shrinkpdf#17]
Hi there,

I have packaged shrinkpdf for Gentoo:
https://git.sthu.org/?p=shuber-gentoo-overlay.git;a=tree;f=app-text/shrinkpdf;h=66b372e6254652314ed663b3bc180b1135e1cdec;hb=HEAD

Since some commits since last release 1.1 from Jun 2022 appear quite important, I would like to ask whether or when you would tag a new release. This would allow me to provide a Gentoo ebuild not being version 9999, but a specific commit with a proper version name.

Best
Stefan

**Comment by aklomp** [comment]
Thanks for the suggestion. You're right, we can do a release. I just released v1.2 :)

**Comment by shuber2** [comment]
Great, thanks. Added shrinkpdf-1.2 in the Gentoo overlay.
