### ISSUE TITLE
Input from absolute URL

### ISSUE THREAD

**Issue by hilmanski** [aklomp/shrinkpdf#9]
HI @aklomp thanks for this library
Any way/any plan to be able to use absolute url as PDF input file?

So we can use this as API without 'upload'/store the PDF at same location first.

Thanks!

**Comment by aklomp** [comment]
Sorry, but not planning to, for the following reasons:

- Handling URLs would introduce a new dependency on some piece of software (something like `wget` or `curl`), and I'd like to avoid additional dependencies.
- Handling URLs would add lots of complexity in an area that is not the core focus of the script. (It's best done elsewhere in my opinion.)
- The script is currently written in such a way that it cannot be used as a pipe filter; changing that would mean a total rewrite, and losing some of the functions, such as the ability to check the output size against the input size.

If you want this functionality, it should be relatively easy to modify the script to work as a pipe filter where the core pipeline looks something like this:

```sh
curl "{$URL}" -o - | gs [...options....] -- -
```

This sets up `curl` to pipe its output to stdout, and `gs` to read its input from stdin.

**Comment by aklomp** [comment]
Sorry, but not planning to, for the following reasons:

- Handling URLs would introduce a new dependency on some piece of software (something like `wget` or `curl`), and I'd like to avoid additional dependencies.
- Handling URLs would add lots of complexity in an area that is not the core focus of the script. (It's best done elsewhere in my opinion.)
- The script is currently written in such a way that it cannot be used as a pipe filter; changing that would mean a total rewrite, and losing some of the functions, such as the ability to check the output size against the input size.

If you want this functionality, it should be relatively easy to modify the script to work as a pipe filter where the core pipeline looks something like this:

```sh
curl "{$URL}" -o - | gs [...options....] -- -
```

This sets up `curl` to pipe its output to stdout, and `gs` to read its input from stdin.
